<Project Sdk="Microsoft.NET.Sdk">

  <Target Name="ValidateBattleTechGameDir" Condition="'$(BattleTechGameDir)' == '' Or !Exists('$(BattleTechGameDir)')">
    <Error Text="BattleTechGameDir variable not set properly" />
  </Target>

  <PropertyGroup Condition="'$(DeployedModPath)' == '' And Exists('$(BattleTechGameDir)\Mods\Core\LowVisibility')">
    <!-- Modpack -->
    <DeployedModPath>$(BattleTechGameDir)\Mods\Core\LowVisibility</DeployedModPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(DeployedModPath)' == '' And Exists('$(BattleTechGameDir)\Mods\LowVisibility')">
    <!-- flat dir -->
    <DeployedModPath>$(BattleTechGameDir)\Mods\LowVisibility</DeployedModPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblySearchPaths>
      $(ReferencePath);
      {HintPathFromItem};
      $(BattleTechGameDir)\BattleTech_Data\Managed
    </AssemblySearchPaths>
    <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
    <DebugType>none</DebugType>
    <AssemblyTitle>LowVisibility</AssemblyTitle>
    <Product>LowVisibility</Product>
    <Copyright>Copyright © 2023</Copyright>
    <AssemblyVersion>2.0.3</AssemblyVersion>
    <FileVersion>2.0.3</FileVersion>
    <LangVersion>13</LangVersion>
  </PropertyGroup>

  <Target Name="AfterBuildMigrated" AfterTargets="CopyFilesToOutputDirectory">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BattleTechGameDir)\Mods\Core\LowVisibility" Condition="'$(BattleTechGameDir)' != '' And Exists('$(BattleTechGameDir)\Mods\Core\LowVisibility')" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(BattleTechGameDir)\Mods_CBDE\Core\LowVisibility" Condition="'$(BattleTechGameDir)' != '' And Exists('$(BattleTechGameDir)\Mods_CBDE\Core\LowVisibility')" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(RogueTechRepo)\Core\LowVisibility" Condition="'$(RogueTechRepo)' != '' And Exists('$(RogueTechRepo)\Core\LowVisibility')" />
  </Target>

  <PropertyGroup>
    <!-- avoids IgnoresAccessChecksToAttribute warnings -->
    <PublicizerRuntimeStrategies>Unsafe</PublicizerRuntimeStrategies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.2.1" />
    <Publicize Include="Assembly-CSharp;UnityEngine.UI" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HarmonyX" Version="2.10.1">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <Reference Include="Assembly-CSharp">
      <HintPath>obj\Debug\net472\PublicizedAssemblies\Assembly-CSharp.DA4053FF61CE77AE57BED9B525AEEA2E\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\..\..\..\..\BATTLETECH\BattleTech_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="CustomActivatableEquipment">
      <HintPath>..\..\..\..\..\..\BATTLETECH\Mods\CustomActivatableEquipment\CustomActivatableEquipment.dll</HintPath>
    </Reference>
    <Reference Include="CustomAmmoCategories">
      <HintPath>..\..\..\..\..\..\BATTLETECH\Mods\CustomAmmoCategories\CustomAmmoCategories.dll</HintPath>
    </Reference>
    <Reference Include="CustomUnits">
      <HintPath>..\..\..\..\..\..\BATTLETECH\Mods\CustomUnits\CustomUnits.dll</HintPath>
    </Reference>
    <Reference Include="IRBTModUtils">
      <HintPath>..\..\..\..\..\..\BATTLETECH\Mods\IRBTModUtils\IRBTModUtils.dll</HintPath>
    </Reference>
    <Reference Include="IRTweaks">
      <HintPath>..\..\..\..\..\..\BATTLETECH\Mods\IRTweaks\IRTweaks.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\..\..\..\..\BATTLETECH\BattleTech_Data\Managed\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System">
      <HintPath>..\..\..\..\..\..\BATTLETECH\BattleTech_Data\Managed\System.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>..\..\..\..\..\..\BATTLETECH\BattleTech_Data\Managed\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>..\..\..\..\..\..\BATTLETECH\BattleTech_Data\Managed\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\..\..\..\BATTLETECH\BattleTech_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>..\..\..\..\..\..\BATTLETECH\BattleTech_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\..\..\..\BATTLETECH\BattleTech_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>..\..\..\..\..\..\BATTLETECH\BattleTech_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\..\..\..\BATTLETECH\BattleTech_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>obj\Debug\net472\PublicizedAssemblies\UnityEngine.UI.7A3535577E24162C9F0CE63F1A5AC061\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>
  
  <ItemGroup>
    <Compile Remove="Patch\HUD\CombatHUDMechTrayPatches.cs" />
  </ItemGroup>
  
</Project>